### ISSUE TITLE
Questions about the overall system

### ISSUE THREAD

**Issue by bleach31** [kashee337/baby_monitor#1]
Thanks for publishing  interesting repository.

Do you have a lsit of required HW and system(SW+HW) arichitecture diagram or some explanation?

**Comment by kashee337** [comment]
Thanks!
Please check [here](https://qiita.com/kashee337/items/a0bb101988b5f5319bbd)!

**Comment by bleach31** [comment]
Oh, that's in Japanese and very clear for me. Thank you.

**Comment by kashee337** [comment]
lol
